trigger:
  branches:
    include:
      - main
      - master
      - refs/heads/*
  tags:
    include:
      - "*"

pool:
  name: Default

variables:
  - group: Terraform_Git_variables

steps:

  - checkout: self
    fetchDepth: 0 # keep full history

  - script: |
      set -euo pipefail

      # Sanity checks
      : "${GITHUB_TOKEN:?Missing GITHUB_TOKEN}"
      : "${GITHUB_REPO:?Missing GITHUB_REPO}"

      git config user.name  "Azure DevOps Mirror"
      git config user.email "azp-mirror@users.noreply.github.com"

      # Populate local refs for ALL remote branches & tags
      git fetch origin +refs/heads/*:refs/heads/* --prune
      git fetch origin --tags --prune

      # Add mirror remote using PAT
      git remote remove mirror 2>/dev/null || true
      git remote add mirror "https://x-access-token:$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git"

      # Push all branches and all tags; prune deletes only branches absent locally
      git push mirror --all --prune
      git push mirror --tags --prune
    displayName: "Mirror Azure Repo → GitHub Repo"